export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DEL_FLASH_MESSAGE = 'DEL_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_CENTERS = 'GET_ALL_CENTERS';
export const VIEW_CENTER_SELECTED = 'VIEW_CENTER_SELECTED';
export const GET_USER_EVENTS = 'GET_USER_EVENTS';