export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DEL_FLASH_MESSAGE = 'DEL_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CENTERS = 'GET_CENTERS';
export const GET_CENTERS_BEGIN = 'GET_CENTERS_BEGIN';
export const GET_CENTERS_ERROR = 'GET_CENTERS_ERROR';
export const VIEW_CENTER_SELECTED = 'VIEW_CENTER_SELECTED';
export const GET_USER_EVENTS = 'GET_USER_EVENTS';